apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pgconsole.fullname" . }}-config
  labels:
    {{- include "pgconsole.labels" . | nindent 4 }}
data:
  pgconsole.toml: |
    {{- .Values.config | nindent 4 }}
